steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --cache=true
  - --cache-ttl=24h
  - --context=front
  - --destination=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/front:${COMMIT_SHA}
  - --dockerfile=front/Dockerfile
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
  - run
  - deploy
  - --execution-environment=gen2
  - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/front:${COMMIT_SHA}
  - --region=$_REGION
substitutions:
  _REGION: us-central1
